set -g prefix C-w
unbind C-b
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
set -g mouse on

# 开启 vi 模式
setw -g mode-keys vi

# 使用 'v' 开始选择
bind-key -T copy-mode-vi v send-keys -X begin-selection
# 使用 'y' 复制并传递到 macOS 系统剪贴板 (pbcopy)
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
# 使用 'Enter' 复制并传递到系统剪贴板
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# 鼠标选中即刻自动复制到系统剪贴板 (松开鼠标左键时触发)
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# 选中网页链接后，按 'o' 键直接在默认浏览器中打开
bind-key -T copy-mode-vi o send-keys -X copy-pipe-and-cancel "xargs open"
